approve_by_comment: true
approve_regex: ^Approved
reject_regex: ^Rejected
reset_on_push: false
reviewers:
  - 
    members:
      - JohnnyRezender
    name: default
    required: 2
    conditions:
            files:
              exclude:
                - ".pullapprove.yml"
  - 
    name: skmapps
    required: 1
    members:
      - JohnnyRezender
    conditions:
        files:  
  -
    name: admin
    required: 1
    members:
        - JohnnyRezender
    conditions:
        files:
          - ".pullapprove.yml" 
            
